[ENH] Add lazy imports to speed up the time taken to load pyjanitor.
pyjanitor-devs/pyjanitor pull request #1060
Opened 2022-04-06 01:09 UTC by ericmjl

# PR Description

Please describe the changes proposed in the pull request:

-
-
-

**This PR resolves #(put issue number here, and remove parentheses).**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

2022-04-06 01:13 UTC, ericmjl commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY -->
🚀 Deployed on https://deploy-preview-1060--pyjanitor.netlify.app

2022-04-06 20:07 UTC, samukweku approved these changes

2022-04-09 04:06 UTC, thatlittleboy requested changes
Really cool idea, TIL @ericmjl !

Requesting changes for now as I'm still mulling over some of the changes suggested here. Leaving my other discussion comments in the issue thread (#1059) so it's more visible. :)

2022-04-09 04:06 UTC, thatlittleboy commented on mkdocs/development/lazy_imports.md
> +Generally speaking, the the _external_ imports are the ones that
```suggestion
Generally speaking, the _external_ imports are the ones that
```
minor typo

2022-04-09 04:06 UTC, thatlittleboy commented on mkdocs/development/lazy_imports.md
> +Note: You may need to install tuna using `pip install -U tuna`.
1. I believe the invocation is meant to be `tuna` rather than `tun`?
2. I think it would be suitable to also include a link to the tuna github / pypi in either of these sentences.

2022-04-09 04:06 UTC, thatlittleboy commented on mkdocs/development/lazy_imports.md
> +![Tuna's Web UI](./images/tuna.png)
This is showing times after lazy loading (it seems the total loading time is 0.5s in the image)? Is it more suitable to show the timings *before* lazy loading instead? 😅 I'm curious to see what the graph looks like if we don't do lazy import, and can help motivate why we choose to lazy import some modules but not the others.

2022-04-09 04:06 UTC, thatlittleboy commented on janitor/functions/add_columns.py
> +np = lazy.load("numpy")
Not sure if I am misunderstanding how lazy loading with `lazy_loader` should work, but does this help in any significant way to reduce import times? I would've thought that at least for `pf` and `pd`, they would be immediately loaded anyway when this file is loaded because they are used directly within this file. 😅

2022-04-09 04:06 UTC, thatlittleboy commented on mkdocs.yml
> +      - Dev Guide: development/devguide.md
This should impact the URL for the devguide, right? In which case we will need to update the url mentioned in the `mkdocs/index.md` file as well.

2022-04-17 04:15 UTC, ericmjl commented on mkdocs/development/lazy_imports.md
> +Note: You may need to install tuna using `pip install -U tuna`.
Done!

2022-04-17 04:16 UTC, ericmjl commented on mkdocs/development/lazy_imports.md
> +![Tuna's Web UI](./images/tuna.png)
Good point! The timings are drastically different. I will add a before/after comparison.

2022-04-17 14:50 UTC, ericmjl commented on janitor/functions/add_columns.py
> +np = lazy.load("numpy")
I've mostly gone empirical with this profiling activity, so I don't think I have a first-principles way of explaining how lazy-loader should work 😂. On the other hand, I have also done another empirical test where I lazy-import pandas-flavor early on in `__init__.py` -- that has the same import speed effect, I think.

2022-06-26 19:56 UTC, ericmjl commented
Apologies to everyone who helped review this PR. I would like to close this PR without merging. My reasons are below.

Firstly, the PR was borne out of a need at work, and that need has gone away through a redesign around a slow import.

Secondly, lazy imports are gaining ground in the broader Python community; I am hopeful that lazy imports will become more and more commonplace and therefore built-in to the language. Given this momentum, I think we should ride the wave rather than be ahead of it.

Thirdly, I've neglected the PR and we've hence had a ton of conflicts accumulate. It might take a bit of time to resolve them.

If we're interested in implementing lazy importing in the library for other good reasons, we can revisit the topic.

2022-06-26 19:56 UTC, closed without merging