INF: Set indenpend environment for building documentation
pyjanitor-devs/pyjanitor pull request #1141
Opened 2022-08-10 07:18 UTC by Zeroto521

# PR Description

Please describe the changes proposed in the pull request:

-
-
-

**This PR resolves #(put issue number here, and remove parentheses).**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

2022-08-10 07:26 UTC, Zeroto521 commented on .github/workflows/docs-preview.yml
> -          activate-environment: pyjanitor-dev
The value of channels and activate-environment use the variable of mkdocs/environment.yml

2022-08-10 07:26 UTC, Zeroto521 commented on .github/workflows/docs-preview.yml
> -          conda activate pyjanitor-dev
default will activate that env

2022-08-10 12:18 UTC, ericmjl commented on CHANGELOG.md
> +-   [INF] Set indenpend environment for building documentation. PR #1141 @Zeroto521
```suggestion
-   [INF] Set independent environment for building documentation. PR #1141 @Zeroto521
```

2022-08-10 12:19 UTC, ericmjl requested changes
Only one change request, and then let's merge!

2022-08-11 01:26 UTC, Zeroto521 commented
Why this test case (tests/functions/test_conditional_join.py::test_multiple_eqs_extension_array) failed in https://github.com/pyjanitor-devs/pyjanitor/runs/7761821318?check_suite_focus=true but passed now?

2022-08-11 02:27 UTC, ericmjl commented
> Why this test case (tests/functions/test_conditional_join.py::test_multiple_eqs_extension_array) failed in https://github.com/pyjanitor-devs/pyjanitor/runs/7761821318?check_suite_focus=true but passed now?

I'm not sure, @Zeroto521 - some tests may be flaky, I guess. Usually a re-run of the CI might do the trick.

With everything green, I'm happy to merge!

2022-08-11 02:27 UTC, ericmjl approved these changes

2022-08-11 02:27 UTC, merged