INF: Set multi-test env to compat dependency and system
pyjanitor-devs/pyjanitor pull request #1143
Opened 2022-08-11 04:38 UTC by Zeroto521

# PR Description

Please describe the changes proposed in the pull request:

-
-
-

**This PR resolves #(put issue number here, and remove parentheses).**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.md`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

2022-08-11 04:48 UTC, Zeroto521 commented
Why does the test action don't work?
Is it a project setting problem?

2022-08-11 10:51 UTC, ericmjl commented
I think it's because the PR is a draft, maybe?

2022-08-11 14:44 UTC, Zeroto521 commented
Well I opened this PR and push a empty commit, but it still can't trigger test ci.

2022-08-12 01:18 UTC, Zeroto521 commented
It seems these functions really have problems.

Need to fix:
- [ ] tests/functions/test_pivot_longer.py::test_names_pattern_str
- [ ] tests/functions/test_pivot_longer.py::test_names_sep
- [ ] tests/functions/test_pivot_longer.py::test_names_transform_numeric
- [ ] tests/functions/test_encode_categorical.py::test_categories_ndim_array_gt_1_in_kwargs
- [ ] tests/utils/test__select_column.py::test_unsorted_dates

I will have a look at `test_encode_categorical.py` and `test__select_column.py`

2022-08-20 10:00 UTC, Zeroto521 commented
I just skip tests/test_documentation_build.py.
I thought we should test documentation in documentation building CI not in the test CI.
I want to keep a clean environment, don't want to mix them (test dependencies and documentation dependencies) up.

2022-10-28 09:38 UTC, Zeroto521 commented
Well, It's hard to say. Sometimes, all envs can pass the health check, and sometimes can't.
It seems all test cases with `@given` need to disable the health check.

2022-10-30 01:04 UTC, Zeroto521 commented
This goal will be done at the next PR.
> Set minimal env: get the minimal version of dependencies

It's ready to be merged.

2022-11-14 23:22 UTC, Zeroto521 commented
Why these py3.8 envs didn't get error?
#1200

2022-11-26 13:16 UTC, Zeroto521 commented
> Why these py3.8 envs didn't get error? #1200

Is https://github.com/pyjanitor-devs/pyjanitor/issues/889 the reason?

2022-12-06 11:05 UTC, ericmjl commented
@Zeroto521 I'm not sure why, but I think testing on py3.8 might become less relevant once py3.12 is released.

2022-12-06 11:09 UTC, ericmjl requested changes
@Zeroto521 only one set of change requests from me, the other being a question for you to address (but not necessarily act on in this PR). 

Thank you for helping out here!

2022-12-06 11:09 UTC, ericmjl commented on .github/workflows/tests.yml
> +        env: [ci/envs/latest.yaml]
@Zeroto521 would you recommend also testing on the development environment as defined in `environment-dev.yml`?

2022-12-06 11:09 UTC, ericmjl commented on .github/workflows/tests.yml
> +        run: pytest -v -r a -n auto --color=yes --durations=0 --cov=janitor --cov-append --cov-report term-missing --cov-report xml tests -m "turtle"
Historically we've been able to reduce testing time by running the `turtle` and `not turtle` tests in parallel. Codecov will also get updated correctly as long as `--cov-append` is called, if I remember correctly. Can we reinstate running `turtle` and `not turtle` tests here, please?

2025-12-17 13:50 UTC, ericmjl commented
@Zeroto521 same as in the other PR which I just closed, this one will be superseded by #1540. Thank you for your efforts here!

2025-12-17 13:50 UTC, closed without merging