Expand column
pyjanitor-devs/pyjanitor pull request #880
Opened 2021-08-18 06:52 UTC by Zeroto521

# PR Description

Please describe the changes proposed in the pull request:

- Set `expand_column`'s `sep` default is `"|"`, same to `pandas.Series.str.get_dummies`.

**This PR resolves #876.**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

2021-08-18 22:18 UTC, ericmjl requested changes
@Zeroto521 thank you for the contribution! I like the change, as it's a sensible one, and I think we'd also appreciate just a bit more user-facing and developer-facing documentation for it. I only have two requested changes, if you could make those, I'm happy to approve the PR.

As is custom, I would also want to make sure we have two reviewers on the PR before we hit merge. Please hang tight; the team is distributed globally (AU, IN, US, etc.), it might take a bit of time for us to get to it!

2021-08-18 22:18 UTC, ericmjl commented on tests/functions/test_expand_column.py
> +def test_sep_default_parameter():
```suggestion
def test_sep_default_parameter():
    """Test that the default parameter is a pipe character `|`."""
```

2021-08-18 22:18 UTC, ericmjl commented on janitor/functions.py
> +    concat: bool = True,
I'd like to suggest that we document explicitly the rationale for setting the separator. It's exactly as you wrote in the changelog, which is sufficient for the docstrings!

2021-08-19 04:10 UTC, samukweku approved these changes

2021-08-19 10:32 UTC, ericmjl commented
@samukweku when the checks are done, please feel free to do the honors! (Not worried about code coverage on this one either, the decrease doesn't seem to be reasonable... must be a bug with codecov I think.)

2021-08-19 10:48 UTC, ericmjl approved these changes

2021-08-19 12:03 UTC, merged