[ENH] Handle null values in concatenate_columns function
pyjanitor-devs/pyjanitor pull request #935
Opened 2021-10-01 06:05 UTC by farhanreynaldo

# PR Description

Please describe the changes proposed in the pull request:

- Add `ignore_empty` parameter to ignore null values during concatenating columns.
- Simplify the current implementation.

**This PR resolves https://github.com/pyjanitor-devs/pyjanitor/issues/756**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.md` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

# Automatic checks

There will be automatic checks run on the PR. These include:

- Building a preview of the docs on Netlify
- Automatically linting the code
- Making sure the code is documented
- Making sure that all tests are passed
- Making sure that code coverage doesn't go down.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

2021-10-02 03:45 UTC, samukweku requested changes
@farhanreynaldo thanks for the PR. Could you kindly add tests for the enhancement.

2021-10-02 04:36 UTC, farhanreynaldo commented
@samukweku This is my first time writing the unittest, is the following test sufficient?

```
@pytest.mark.functions
def test_concatenate_columns_null_values(missingdata_df):
    df = missingdata_df.concatenate_columns(
        column_names=["a", "decorated-elephant"],
        sep="-",
        new_column_name="index",
    )
    expected_values = ['1.0-1', '2.0-2', '3'] * 3
    assert expected_values == df['index'].tolist()
```

2021-10-02 05:09 UTC, samukweku commented
@farhanreynaldo yea, it should, as long as the tests pass

2021-10-03 00:49 UTC, samukweku approved these changes

2021-10-10 02:56 UTC, ericmjl approved these changes

2021-10-10 02:56 UTC, ericmjl commented on janitor/functions.py
> +    )
Wow, that's pretty smaht. Nice work here, @farhanreynaldo!

2021-10-10 02:56 UTC, merged

2021-10-10 02:56 UTC, ericmjl commented
Thank you, @farhanreynaldo! Great PR - very nice and defined unit of work :smile:, and you executed well on it!